spring:
  #  profiles:
  #    active: local
#  messages:
#    basename: messages,errors  # 에러메시지

  data:
    web:
      pageable:
        default-page-size: 20 # 기본 페이지 사이즈

  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace #띄어쓰기 2칸


---
spring:
  profiles:
    active: local
  datasource:
    username: root
    password: 12341234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/book_management

server:
  port: 8082

  jpa:
    hibernate:
      ddl-auto: update  # create: 자동으로 테이블 만들어줌