spring:
  #  profiles:
  #    active: local
#  messages:
#    basename: messages,errors  # 에러메시지

  data:
    web:
      pageable:
        default-page-size: 20 # 기본 페이지 사이즈

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Spring Boot RabbitMQ 설정
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  cache:
    type: redis
    redis:
      time-to-live: 3600 # 데이터 유지 시간(sec)
      cache-null-values: true # null 캐싱 여부
      host: localhost
      port: 6379



logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace #띄어쓰기 2칸

---
spring:
  profiles:
    active: local
  datasource:
    username: root
    password: 12341234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/book_management

  jpa:
    hibernate:
      ddl-auto: update  # create: 자동으로 테이블 만들어줌

server:
  port: 8082